# Generated by Django 3.2.9 on 2022-02-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('TeamId', models.TextField(max_length=4, primary_key=True, serialize=False)),
                ('TeamName', models.TextField(choices=[('RR', 'Rajsthan Royals'), ('MI', 'Mumbai Indians'), ('RCB', 'Royal Challengers Bangalore'), ('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('SRH', 'Sun Risers Hyderabad'), ('KKR', 'Kolkata Knight Riders'), ('PBK', 'Punjab Kings')], max_length=10)),
                ('TeamIcon', models.ImageField(blank=True, upload_to='icons')),
                ('TopBatsman', models.TextField(blank=True, max_length=100)),
                ('TopBowler', models.TextField(blank=True, max_length=100)),
                ('TourWon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('price', models.TextField(default=0, max_length=100)),
                ('isPlaying', models.BooleanField(default=True)),
                ('description', models.TextField(choices=[('BT', 'Batsman'), ('BO', 'Bowler'), ('AR', 'All Rounder')], max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Teams.teams')),
            ],
        ),
    ]
