# Generated by Django 3.2.9 on 2022-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='pic',
            field=models.ImageField(default='default-player.png', upload_to='players_pics'),
        ),
    ]
