# Generated by Django 3.2.9 on 2022-02-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_players_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='TeamName',
            field=models.TextField(choices=[('Rajsthan Royals', 'Rajsthan Royals'), ('Mumbai Indians', 'Mumbai Indians'), ('Royal Challengers Bangalore', 'Royal Challengers Bangalore'), ('Chennai Super Kings', 'Chennai Super Kings'), ('Delhi Capitals', 'Delhi Capitals'), ('Sun Risers Hyderabad', 'Sun Risers Hyderabad'), ('Kolkata Knight Riders', 'Kolkata Knight Riders'), ('Punjab Kings', 'Punjab Kings')], max_length=100),
        ),
    ]
